apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "20"
    imagePullPolicy: IfNotPresent
    name: busybox2
  restartPolicy: Always
